**About Dataset**
Dataset Description
Tables and Features:
Deaths

peak_id: ID of a peak
peak_name: Peak name
name: Alpinist name
yr_season: Year and Season
is_o2_used: If oxygen has been used
Peaks

host_contries: Countries from which ascents are possible
first_asc_yr: The first year of ascent
Expeditions

peak_id: ID of a peak
peak_name: Peak name
nationality: The principle nationality of the expedition (main nationality)
year: Expedition year
season: Expedition season
host_cntr: Country from which ascent has begun
other_cntrs: Countries that took part in the expedition (members nationality)
sponsor: Expedition sponsor
leaders: Leader/leaders of the expedition
rte_1_name: The first route name (similar for the rest features with the same prefix)
team_asc_1: The times that a team ascended for a certain route name (similar for the rest features with the same prefix)
is_disputed: Success Disputed or Unverified
is_claim: Expedition claims that summited, however, without any evidence (probably a lie)
is_commercial_rte: If the expedition was commercial
is_standard_rte: If the route is standard (S Col-SE Ridge/N Col-NE Ridge/N Col)
other_smts: Other peaks summited
approach: Main expedition intermediate points to reach the mountain
bc_arrived: Arrival date at the base camp
bc_left: Departure date from the base camp
total_days: Total number of days spent by the expedition
exp_result: The result of the expedition
is_traverse: If the traverse has been made (?)
is_ski_snowboard: If the descent has been made using ski/snowboard
is_parapente: If the descent has been made using parapente
term_note: Summit termination details/results
summit_day: Day of the summit
time: Summit time
max_elev_reached: Max elevation reached by the expedition
summit_days: Day of the summit according to total_days feature
total_mbrs: Total number of expedition members
mbrs_summited: Total number of expedition members that have summited
mbrs_deaths: Total number of expedition members that died
high_camps: Number of high camps
hired_abc: ?
hired_summits: ?
hired_deaths: ?
rope_fixed: total rope length that has been fixed on the mountain/route
is_no_hired_abc: ?
is_o2_not_used: If O2 has not been used
is_o2_climbing: If O2 has been used during climbing
is_o2_descent: If O2 has been used only on descent
is_o2_medical: If O2 has been used for medical reasons
is_o2_unkwn: It's unknown whether O2 has been used or not
had_o2: O2 has been taken but unused
camp_sites: Expedition camps locations
accidents: Accident description
achievements: Achievement description
agency: Commercial agency name
members: Expedition members (name: L - Leader, S - Summited, D - Died)

Acerca del conjunto de datos
Descripción del conjunto de datos
Tablas y características:
Defunciones

peak_id: ID de un pico
peak_name: Nombre del pico
name: Nombre del alpinista
yr_season: Año y estación
is_o2_used: Si se ha utilizado oxígeno
Picos

host_contries: Países desde los que se puede ascender
first_asc_yr: El primer año de ascensión
Expediciones

peak_id: ID de un pico
peak_name: Nombre del pico
nationality (nacionalidad): La nacionalidad principal de la expedición (nacionalidad principal)
year: Año de la expedición Año de la expedición
season: Temporada de la expedición
host_cntr: País desde el que se ha iniciado la ascensión
other_cntrs: Países que participaron en la expedición (nacionalidad de los miembros)
patrocinador: Patrocinador de la expedición
líderes: Líder/es de la expedición
rte_1_name: El primer nombre de ruta (similar para el resto de características con el mismo prefijo)
team_asc_1: Las veces que un equipo ascendió por un determinado nombre de ruta (similar para el resto de características con el mismo prefijo)
is_disputed: Éxito Disputado o No Verificado
is_claim: Expedición afirma que hizo cumbre, sin embargo, sin ninguna prueba (probablemente una mentira)
is_commercial_rte: Si la expedición fue comercial
is_standard_rte: Si la ruta es estándar (S Col-SE Ridge/N Col-NE Ridge/N Col)
other_smts: Otras cumbres coronadas
approach: Puntos intermedios de la expedición principal para llegar a la montaña
bc_arrived: Fecha de llegada al campo base
bc_left: Fecha de salida del campo base
total_días: Número total de días que ha pasado la expedición
exp_resultado: El resultado de la expedición
is_traverse: Si se ha realizado la travesía (?)
is_ski_snowboard: Si el descenso se ha realizado con esquí/snowboard
is_parapente: Si el descenso se ha realizado en parapente
term_note: Detalles/resultados de la finalización de la cumbre
summit_day: Día de la cumbre
time: Hora de la cumbre
max_elev_reached: Altitud máxima alcanzada por la expedición
días_cumbre: Día de la cumbre según la función total_days
total_mbrs: Número total de expedicionarios
mbrs_summited: Número total de expedicionarios que han hecho cumbre
mbrs_deaths: Número total de expedicionarios que han fallecido
high_camps: Número de campamentos de altura
abc_contratados: ?
sumas_contratadas: ?
muertes_contratadas: ?
rope_fixed: longitud total de cuerda que se ha fijado en la montaña/ruta
is_no_hired_abc: ?
is_o2_not_used: Si no se ha utilizado O2
is_o2_climbing: Si se ha utilizado O2 durante la escalada
is_o2_descent: Si se ha utilizado O2 sólo en el descenso
is_o2_medical: Si se ha utilizado O2 por razones médicas
is_o2_unkwn: Se desconoce si se ha utilizado O2 o no
had_o2: Se ha tomado O2 pero no se ha utilizado
camp_sites: Lugares de acampada de la expedición
accidents (accidentes): Descripción del accidente
logros: Descripción del logro
agencia Nombre de la agencia comercial
miembros: Miembros de la expedición (nombre: L - Líder, S - Cumbre, D - Muerto)

In [1]:
import pandas as pd
import numpy as np
import sklearn.model_selection as train_test_split
from openpyxl import load_workbook
from pathlib import Path
import io
import matplotlib
import seaborn as sns   
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
import sklearn.svm as svm
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler   
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import BayesianRidge
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression 
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso

In [2]:
df_exped = pd.read_csv('exped.csv')
df_exped.head()

C:\Users\Fabrizio\AppData\Local\Temp\ipykernel_14452\984487663.py:1: DtypeWarning: Columns (8,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df_exped = pd.read_csv('exped.csv')

,expid,peakid,year,season,host,route1,route2,route3,route4,nation,...,accidents,achievment,agency,comrte,stdrte,primrte,primmem,primref,primid,chksum
0,ANN260101,ANN2,1960,Spring,Nepal,NW Ridge-W Ridge,NaN,NaN,NaN,UK,...,NaN,NaN,NaN,False,False,False,False,False,NaN,2442047
1,ANN269301,ANN2,1969,Autumn,Nepal,NW Ridge-W Ridge,NaN,NaN,NaN,Yugoslavia,...,Draslar frostbitten hands and feet,NaN,NaN,False,False,False,False,False,NaN,2445501
2,ANN273101,ANN2,1973,Spring,Nepal,W Ridge-N Face,NaN,NaN,NaN,Japan,...,NaN,NaN,NaN,False,False,False,False,False,NaN,2446797
3,ANN278301,ANN2,1978,Autumn,Nepal,N Face-W Ridge,NaN,NaN,NaN,UK,...,NaN,NaN,NaN,False,False,False,False,False,NaN,2448822
4,ANN279301,ANN2,1979,Autumn,Nepal,N Face-W Ridge,NW Ridge of A-IV,NaN,NaN,UK,...,NaN,NaN,NaN,False,False,False,False,False,NaN,2449204

In [3]:

class info_modulo():
    def __init__(self, data):
        # inicialización
        self.data = data

    # Crear un dataframe para la df.info()
    def frame_info(self, data):
        buf = io.StringIO()
        data.info(buf=buf)
        s = buf.getvalue()
        lines = [line.split() for line in s.splitlines()[3:-2]]
        return pd.DataFrame(lines)

    def variables_null(self):
        null_columns = self.data.columns[self.data.isnull().any()]
        df_2 = pd.DataFrame(columns=['Nombre Variable', 'Cantidad de Nulos'])
        for col in null_columns:
            nueva_fila = {
                'Nombre Variable': col,
                'Cantidad de Nulos': self.data[col].isnull().sum()
            }
            df_2 = pd.concat([df_2, pd.DataFrame([nueva_fila])], ignore_index=True)
        return df_2

    def variables_nan(self):
        obj_df = self.data.select_dtypes(include=['object'])
        nan_columns = [col for col in obj_df.columns if obj_df[col].isnull().any() or (obj_df[col] == '').any()]
        df_2 = pd.DataFrame(columns=['Nombre Variable', 'Cantidad de Nan o vacíos'])
        for col in nan_columns:
            cantidad = obj_df[col].isnull().sum() + (obj_df[col] == '').sum()
            nueva_fila = {
                'Nombre Variable': col,
                'Cantidad de Nan o vacíos': cantidad
            }
            df_2 = pd.concat([df_2, pd.DataFrame([nueva_fila])], ignore_index=True)
        return df_2

    def info_dataframe(self, ruta = ''):
        print(f"Tamaño: {self.data.shape}")
        print("\n")
        print(f"Variables nulos: ")
        print(self.variables_null())
        print("\n")
        print(f"Variables NAN: ")
        print(self.variables_nan())
        print("\n")    
        print(f"Informacion dataframe: ")
        print(self.data.info())
        print("\n")
        print(f"Datos: ")
        print(self.data.head(10))
        print("\n")

In [4]:
df_exped.info_modulo = info_modulo(df_exped)
df_exped.info_modulo.info_dataframe()

Tamaño: (11425, 65)


Variables nulos:
   Nombre Variable Cantidad de Nulos
0           route1               150
1           route2             11065
2           route3             11395
3           route4             11420
4          leaders                24
5          sponsor               816
6          ascent1              8647
7          ascent2             11324
8          ascent3             11414
9          ascent4             11421
10       countries              7312
11        approach              5989
12          bcdate              1630
13         smtdate               755
14         smttime              6443
15         smtdays              1754
16         totdays              3019
17        termdate              2975
18        termnote              6777
19       othersmts              9226
20       campsites               379
21       accidents              8424
22      achievment             10449
23          agency              1729
24          primid             10672


Variables NAN:
   Nombre Variable Cantidad de Nan o vacíos
0           route1                      150
1           route2                    11065
2           route3                    11395
3           route4                    11420
4          leaders                       24
5          sponsor                      816
6          ascent1                     8647
7          ascent2                    11324
8          ascent3                    11414
9          ascent4                    11421
10       countries                     7312
11        approach                     5989
12          bcdate                     1630
13         smtdate                      755
14        termdate                     2975
15        termnote                     6777
16       othersmts                     9226
17       campsites                      379
18       accidents                     8424
19      achievment                    10449
20          agency                     1729
21          primid                    10672


Informacion dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11425 entries, 0 to 11424
Data columns (total 65 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   expid       11425 non-null  object
 1   peakid      11425 non-null  object
 2   year        11425 non-null  int64
 3   season      11425 non-null  object
 4   host        11425 non-null  object
 5   route1      11275 non-null  object
 6   route2      360 non-null    object
 7   route3      30 non-null     object
 8   route4      5 non-null      object
 9   nation      11425 non-null  object
 10  leaders     11401 non-null  object
 11  sponsor     10609 non-null  object
 12  success1    11425 non-null  bool
 13  success2    11425 non-null  bool
 14  success3    11425 non-null  bool
 15  success4    11425 non-null  bool
 16  ascent1     2778 non-null   object
 17  ascent2     101 non-null    object
 18  ascent3     11 non-null     object
 19  ascent4     4 non-null      object
 20  claimed     11425 non-null  bool
 21  disputed    11425 non-null  bool
 22  countries   4113 non-null   object
 23  approach    5436 non-null   object
 24  bcdate      9795 non-null   object
 25  smtdate     10670 non-null  object
 26  smttime     4982 non-null   float64
 27  smtdays     9671 non-null   float64
 28  totdays     8406 non-null   float64
 29  termdate    8450 non-null   object
 30  termreason  11425 non-null  object
 31  termnote    4648 non-null   object
 32  highpoint   11425 non-null  int64
 33  traverse    11425 non-null  bool
 34  ski         11425 non-null  bool
 35  parapente   11425 non-null  bool
 36  camps       11425 non-null  int64
 37  rope        11425 non-null  int64
 38  totmembers  11425 non-null  int64
 39  smtmembers  11425 non-null  int64
 40  mdeaths     11425 non-null  int64
 41  tothired    11425 non-null  int64
 42  smthired    11425 non-null  int64
 43  hdeaths     11425 non-null  int64
 44  nohired     11425 non-null  bool
 45  o2used      11425 non-null  bool
 46  o2none      11425 non-null  bool
 47  o2climb     11425 non-null  bool
 48  o2descent   11425 non-null  bool
 49  o2sleep     11425 non-null  bool
 50  o2medical   11425 non-null  bool
 51  o2taken     11425 non-null  bool
 52  o2unkwn     11425 non-null  bool
 53  othersmts   2199 non-null   object
 54  campsites   11046 non-null  object
 55  accidents   3001 non-null   object
 56  achievment  976 non-null    object
 57  agency      9696 non-null   object
 58  comrte      11425 non-null  bool
 59  stdrte      11425 non-null  bool
 60  primrte     11425 non-null  bool
 61  primmem     11425 non-null  bool
 62  primref     11425 non-null  bool
 63  primid      753 non-null    object
 64  chksum      11425 non-null  int64
dtypes: bool(23), float64(3), int64(11), object(28)
memory usage: 3.9+ MB
None


Datos:
       expid peakid  year  season   host              route1  \
0  ANN260101   ANN2  1960  Spring  Nepal    NW Ridge-W Ridge
1  ANN269301   ANN2  1969  Autumn  Nepal    NW Ridge-W Ridge
2  ANN273101   ANN2  1973  Spring  Nepal      W Ridge-N Face
3  ANN278301   ANN2  1978  Autumn  Nepal      N Face-W Ridge
4  ANN279301   ANN2  1979  Autumn  Nepal      N Face-W Ridge
5  ANN280101   ANN2  1980  Spring  Nepal      N Face-W Ridge
6  ANN280102   ANN2  1980  Spring  Nepal  SE Spur (to 6000m)
7  ANN281302   ANN2  1981  Autumn  Nepal    NW Ridge-W Ridge
8  ANN281301   ANN2  1981  Autumn  Nepal     S Ridge/SE Face
9  ANN282301   ANN2  1982  Autumn  Nepal              S Face

                      route2 route3 route4      nation  ...  \
0                        NaN    NaN    NaN          UK  ...
1                        NaN    NaN    NaN  Yugoslavia  ...
2                        NaN    NaN    NaN       Japan  ...
3                        NaN    NaN    NaN          UK  ...
4           NW Ridge of A-IV    NaN    NaN          UK  ...
5                        NaN    NaN    NaN       Japan  ...
6  S Face-W Ridge (to 7250m)    NaN    NaN      Poland  ...
7                        NaN    NaN    NaN       Italy  ...
8                        NaN    NaN    NaN       Japan  ...
9                        NaN    NaN    NaN       Japan  ...

                              accidents achievment  agency  comrte  stdrte  \
0                                   NaN        NaN     NaN   False   False
1    Draslar frostbitten hands and feet        NaN     NaN   False   False
2                                   NaN        NaN     NaN   False   False
3                                   NaN        NaN     NaN   False   False
4                                   NaN        NaN     NaN   False   False
5        Tanabe (leader) killed by fall        NaN     NaN   False   False
6                 Injuries by avalanche        NaN     NaN   False   False
7                                   NaN        NaN     NaN   False   False
8  Icikawa killed by 500m fall at 7400m        NaN     NaN   False   False
9                                   NaN        NaN     NaN   False   False

   primrte primmem primref primid   chksum
0    False   False   False    NaN  2442047
1    False   False   False    NaN  2445501
2    False   False   False    NaN  2446797
3    False   False   False    NaN  2448822
4    False   False   False    NaN  2449204
5    False   False   False    NaN  2449394
6    False   False   False    NaN  2449408
7    False   False   False    NaN  2449912
8    False   False   False    NaN  2449930
9    False   False   False    NaN  2450289

[10 rows x 65 columns]

In [5]:
df_himalayan_data_dictionary = pd.read_csv('himalayan_data_dictionary.csv')
df_himalayan_data_dictionary.head()

   Table     Field                        Description
0  peaks       NaN                                NaN
1  peaks    peakid              Peak ID (primary key)
2  peaks    pkname  Foreign (common) name of the peak
3  peaks   pkname2             Local name of the peak
4  peaks  location      Location of the climbing area

In [6]:
df_members = pd.read_csv('members.csv')
df_members.head()

C:\Users\Fabrizio\AppData\Local\Temp\ipykernel_14452\2542370295.py:1: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  df_members = pd.read_csv('members.csv')

,expid,membid,peakid,myear,mseason,fname,lname,sex,yob,citizen,...,death,deathdate,deathtime,deathtype,deathhgtm,deathclass,msmtbid,msmtterm,hcn,mchksum
0,AMAD01101,2,AMAD,2001,Spring,Rohan,Buckley,M,1972.0,Australia,...,False,NaN,NaN,NaN,0,NaN,No summit bid,Did not climb or intent to summit,NaN,2439554
1,AMAD01101,1,AMAD,2001,Spring,Marc Cameron,Fairhead,M,1968.0,Australia,...,False,NaN,NaN,NaN,0,NaN,Aborted at high camp,"Bad conditions (deep snow, avalanches, falling...",NaN,2438062
2,AMAD01101,3,AMAD,2001,Spring,Mark,Schroeder,M,1960.0,Australia,...,False,NaN,NaN,NaN,0,NaN,Aborted at high camp,"Bad conditions (deep snow, avalanches, falling...",NaN,2435183
3,AMAD01101,4,AMAD,2001,Spring,Colin,Smith,M,1966.0,Australia,...,False,NaN,NaN,NaN,0,NaN,No summit bid,Did not climb or intent to summit,NaN,2437475
4,AMAD01101,5,AMAD,2001,Spring,Naomi,Smith,F,1970.0,Australia,...,False,NaN,NaN,NaN,0,NaN,No summit bid,Did not climb or intent to summit,NaN,2438996

In [7]:
info_modulo_members = info_modulo(df_members)
info_modulo_members.info_dataframe()

Tamaño: (89000, 61)


Variables nulos:
   Nombre Variable Cantidad de Nulos
0            fname               103
1            lname              1124
2              yob              5408
3          citizen                 7
4        residence              8830
5       occupation             30739
6       mperhighpt             24946
7        msmtdate1             29269
8        msmtdate2             88551
9        msmtdate3             88978
10       msmttime1             62488
11       msmttime2             88756
12       msmttime3             88993
13         mo2note             73653
14       deathdate             87868
15       deathtime             88432
16       deathtype             87842
17      deathclass             87842
18        msmtterm               176
19             hcn             88705


Variables NAN:
   Nombre Variable Cantidad de Nan o vacíos
0            fname                      103
1            lname                     1124
2          citizen                        7
3        residence                     8830
4       occupation                    30739
5        msmtdate1                    29269
6        msmtdate2                    88551
7        msmtdate3                    88978
8          mo2note                    73653
9        deathdate                    87868
10       deathtype                    87842
11      deathclass                    87842
12        msmtterm                      176


Informacion dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89000 entries, 0 to 88999
Data columns (total 61 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   expid       89000 non-null  object
 1   membid      89000 non-null  int64
 2   peakid      89000 non-null  object
 3   myear       89000 non-null  int64
 4   mseason     89000 non-null  object
 5   fname       88897 non-null  object
 6   lname       87876 non-null  object
 7   sex         89000 non-null  object
 8   yob         83592 non-null  float64
 9   citizen     88993 non-null  object
 10  status      89000 non-null  object
 11  residence   80170 non-null  object
 12  occupation  58261 non-null  object
 13  leader      89000 non-null  bool
 14  deputy      89000 non-null  bool
 15  bconly      89000 non-null  bool
 16  nottobc     89000 non-null  bool
 17  support     89000 non-null  bool
 18  disabled    89000 non-null  bool
 19  hired       89000 non-null  bool
 20  sherpa      89000 non-null  bool
 21  tibetan     89000 non-null  bool
 22  msuccess    89000 non-null  bool
 23  mclaimed    89000 non-null  bool
 24  mdisputed   89000 non-null  bool
 25  msolo       89000 non-null  bool
 26  mtraverse   89000 non-null  bool
 27  mski        89000 non-null  bool
 28  mparapente  89000 non-null  bool
 29  mspeed      89000 non-null  bool
 30  mhighpt     89000 non-null  bool
 31  mperhighpt  64054 non-null  float64
 32  msmtdate1   59731 non-null  object
 33  msmtdate2   449 non-null    object
 34  msmtdate3   22 non-null     object
 35  msmttime1   26512 non-null  float64
 36  msmttime2   244 non-null    float64
 37  msmttime3   7 non-null      float64
 38  mroute1     89000 non-null  int64
 39  mroute2     89000 non-null  int64
 40  mroute3     89000 non-null  int64
 41  mascent1    89000 non-null  int64
 42  mascent2    89000 non-null  int64
 43  mascent3    89000 non-null  int64
 44  mo2used     89000 non-null  bool
 45  mo2none     89000 non-null  bool
 46  mo2climb    89000 non-null  bool
 47  mo2descent  89000 non-null  bool
 48  mo2sleep    89000 non-null  bool
 49  mo2medical  89000 non-null  bool
 50  mo2note     15347 non-null  object
 51  death       89000 non-null  bool
 52  deathdate   1132 non-null   object
 53  deathtime   568 non-null    float64
 54  deathtype   1158 non-null   object
 55  deathhgtm   89000 non-null  int64
 56  deathclass  1158 non-null   object
 57  msmtbid     89000 non-null  object
 58  msmtterm    88824 non-null  object
 59  hcn         295 non-null    float64
 60  mchksum     89000 non-null  int64
dtypes: bool(25), float64(7), int64(10), object(19)
memory usage: 26.6+ MB
None


Datos:
       expid  membid peakid  myear mseason             fname           lname  \
0  AMAD01101       2   AMAD   2001  Spring             Rohan         Buckley
1  AMAD01101       1   AMAD   2001  Spring      Marc Cameron        Fairhead
2  AMAD01101       3   AMAD   2001  Spring              Mark       Schroeder
3  AMAD01101       4   AMAD   2001  Spring             Colin           Smith
4  AMAD01101       5   AMAD   2001  Spring             Naomi           Smith
5  AMAD01102       1   AMAD   2001  Spring            Sergei       Menchenin
6  AMAD01102       2   AMAD   2001  Spring  Ekaterina (Kate)     Vorotnikova
7  AMAD01102       3   AMAD   2001  Spring              Stas       Yurkevich
8  AMAD01103       2   AMAD   2001  Spring              Quim  Bretcha Planas
9  AMAD01103       3   AMAD   2001  Spring           Eduardo   Castano Boldu

  sex     yob    citizen  ...  death deathdate deathtime  deathtype  \
0   M  1972.0  Australia  ...  False       NaN       NaN        NaN
1   M  1968.0  Australia  ...  False       NaN       NaN        NaN
2   M  1960.0  Australia  ...  False       NaN       NaN        NaN
3   M  1966.0  Australia  ...  False       NaN       NaN        NaN
4   F  1970.0  Australia  ...  False       NaN       NaN        NaN
5   M  1958.0        USA  ...  False       NaN       NaN        NaN
6   F  1956.0     Russia  ...  False       NaN       NaN        NaN
7   M  1968.0        USA  ...  False       NaN       NaN        NaN
8   M  1970.0      Spain  ...  False       NaN       NaN        NaN
9   M  1970.0      Spain  ...  False       NaN       NaN        NaN

   deathhgtm  deathclass               msmtbid  \
0          0         NaN         No summit bid
1          0         NaN  Aborted at high camp
2          0         NaN  Aborted at high camp
3          0         NaN         No summit bid
4          0         NaN         No summit bid
5          0         NaN         No summit bid
6          0         NaN         No summit bid
7          0         NaN         No summit bid
8          0         NaN           Unspecified
9          0         NaN           Unspecified

                                            msmtterm  hcn  mchksum
0                  Did not climb or intent to summit  NaN  2439554
1  Bad conditions (deep snow, avalanches, falling...  NaN  2438062
2  Bad conditions (deep snow, avalanches, falling...  NaN  2435183
3                  Did not climb or intent to summit  NaN  2437475
4                  Did not climb or intent to summit  NaN  2438996
5       Altitude (AMS symptoms, breathing or unwell)  NaN  2434617
6                                            Unknown  NaN  2433862
7  Assisting, guiding, supporting or accompanying...  NaN  2438078
8                                        Unspecified  NaN  2438849
9                                        Unspecified  NaN  2438982

[10 rows x 61 columns]

In [8]:
df_peaks = pd.read_csv('peaks.csv')
df_peaks.head()

,peakid,pkname,pkname2,location,heightm,heightf,himal,region,open,unlisted,...,phost,pstatus,pyear,pseason,pmonth,pday,pexpid,pcountry,psummiters,psmtnote
0,ACHN,Aichyn,"Aychin, Ashvin",Chandi Himal (SW of Changwathang),6055,19865,Nalakankar/Chandi/Changla,Kanjiroba-Far West,True,False,...,Nepal only,Climbed,2015.0,Autumn,Sep,3.0,ACHN15301,Japan,"Hiroki Senda, et al",NaN
1,AMAD,Ama Dablam,Amai Dablang,Khumbu Himal,6814,22356,Khumbu,Khumbu-Rolwaling-Makalu,True,False,...,Nepal only,Climbed,1961.0,Spring,Mar,13.0,AMAD61101,"New Zealand, USA, UK","Mike Gill, Wally Romanes, Barry Bishop, Michae...",NaN
2,AMOT,Amotsang,Amatson,Damodar Himal (NW of Pokharhan),6393,20974,Damodar,Annapurna-Damodar-Peri,True,False,...,Nepal only,Climbed,2019.0,Autumn,Oct,24.0,AMOT19301,Germany,Jost Kobusch,Possibly climbed earlier
3,AMPG,Amphu Gyabjen,Amphu Gyabien,Khumbu Himal (N of Ama Dablam),5630,18471,Khumbu,Khumbu-Rolwaling-Makalu,True,False,...,Nepal only,Climbed,1953.0,Spring,Apr,11.0,AMPG53101,UK,"John Hunt, Tom Bourdillon",NaN
4,AMPH,Amphu I,NaN,"Khumbu Himal (E of Amphu Laptsa, W of Baruntse)",6740,22113,Khumbu,Khumbu-Rolwaling-Makalu,True,False,...,Nepal only,Climbed,2013.0,Autumn,Oct,9.0,AMPH13301,S Korea,"An Chi-Young, Kim Young-Mi, Oh Young-Hoon",NaN

In [9]:

info_modulo_peaks = info_modulo(df_peaks)
info_modulo_peaks.info_dataframe()

Tamaño: (480, 23)


Variables nulos:
   Nombre Variable Cantidad de Nulos
0          pkname2               223
1         location                 1
2         trekyear               451
3         restrict               205
4            pyear               118
5          pseason               117
6           pmonth               123
7             pday               140
8           pexpid               120
9         pcountry               118
10      psummiters                 3
11        psmtnote               404


Variables NAN:
  Nombre Variable Cantidad de Nan o vacíos
0         pkname2                      223
1        location                        1
2        restrict                      205
3         pseason                      117
4          pmonth                      123
5          pexpid                      120
6        pcountry                      118
7      psummiters                        3
8        psmtnote                      404


Informacion dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   peakid      480 non-null    object
 1   pkname      480 non-null    object
 2   pkname2     257 non-null    object
 3   location    479 non-null    object
 4   heightm     480 non-null    int64
 5   heightf     480 non-null    int64
 6   himal       480 non-null    object
 7   region      480 non-null    object
 8   open        480 non-null    bool
 9   unlisted    480 non-null    bool
 10  trekking    480 non-null    bool
 11  trekyear    29 non-null     float64
 12  restrict    275 non-null    object
 13  phost       480 non-null    object
 14  pstatus     480 non-null    object
 15  pyear       362 non-null    float64
 16  pseason     363 non-null    object
 17  pmonth      357 non-null    object
 18  pday        340 non-null    float64
 19  pexpid      360 non-null    object
 20  pcountry    362 non-null    object
 21  psummiters  477 non-null    object
 22  psmtnote    76 non-null     object
dtypes: bool(3), float64(3), int64(2), object(15)
memory usage: 76.5+ KB
None


Datos:
  peakid         pkname          pkname2  \
0   ACHN         Aichyn   Aychin, Ashvin
1   AMAD     Ama Dablam     Amai Dablang
2   AMOT       Amotsang          Amatson
3   AMPG  Amphu Gyabjen    Amphu Gyabien
4   AMPH        Amphu I              NaN
5   AMPM   Amphu Middle      Amphu North
6   ANID  Anidesh Chuli  White Wave Peak
7   ANN1    Annapurna I              NaN
8   ANN2   Annapurna II              NaN
9   ANN3  Annapurna III              NaN

                                          location  heightm  heightf  \
0                Chandi Himal (SW of Changwathang)     6055    19865
1                                     Khumbu Himal     6814    22356
2                  Damodar Himal (NW of Pokharhan)     6393    20974
3                   Khumbu Himal (N of Ama Dablam)     5630    18471
4  Khumbu Himal (E of Amphu Laptsa, W of Baruntse)     6740    22113
5                Khumbu Himal (NW of Amphu Laptsa)     6202    20348
6            Kangchenjunga Himal (W of Kangbachen)     6808    22336
7                                  Annapurna Himal     8091    26545
8                                  Annapurna Himal     7937    26040
9                                  Annapurna Himal     7555    24787

                       himal                   region   open  unlisted  ...  \
0  Nalakankar/Chandi/Changla       Kanjiroba-Far West   True     False  ...
1                     Khumbu  Khumbu-Rolwaling-Makalu   True     False  ...
2                    Damodar   Annapurna-Damodar-Peri   True     False  ...
3                     Khumbu  Khumbu-Rolwaling-Makalu   True     False  ...
4                     Khumbu  Khumbu-Rolwaling-Makalu   True     False  ...
5                     Khumbu  Khumbu-Rolwaling-Makalu  False      True  ...
6    Kangchenjunga/Simhalila      Kangchenjunga-Janak   True     False  ...
7                  Annapurna   Annapurna-Damodar-Peri   True     False  ...
8                  Annapurna   Annapurna-Damodar-Peri   True     False  ...
9                  Annapurna   Annapurna-Damodar-Peri   True     False  ...

        phost    pstatus   pyear pseason pmonth  pday     pexpid  \
0  Nepal only    Climbed  2015.0  Autumn    Sep   3.0  ACHN15301
1  Nepal only    Climbed  1961.0  Spring    Mar  13.0  AMAD61101
2  Nepal only    Climbed  2019.0  Autumn    Oct  24.0  AMOT19301
3  Nepal only    Climbed  1953.0  Spring    Apr  11.0  AMPG53101
4  Nepal only    Climbed  2013.0  Autumn    Oct   9.0  AMPH13301
5  Nepal only    Climbed  2008.0  Spring    Apr  20.0  AMPM08101
6  Nepal only  Unclimbed     NaN     NaN    NaN   NaN        NaN
7  Nepal only    Climbed  1950.0  Spring    Jun   3.0  ANN150101
8  Nepal only    Climbed  1960.0  Spring    May  17.0  ANN260101
9  Nepal only    Climbed  1961.0  Spring    May   6.0  ANN361101

               pcountry                                         psummiters  \
0                 Japan                                Hiroki Senda, et al
1  New Zealand, USA, UK  Mike Gill, Wally Romanes, Barry Bishop, Michae...
2               Germany                                       Jost Kobusch
3                    UK                          John Hunt, Tom Bourdillon
4               S Korea          An Chi-Young, Kim Young-Mi, Oh Young-Hoon
5               Germany                      Olaf Rieck, Alexander Graeber
6                   NaN                                          Unclimbed
7                France                     Maurice Herzog, Louis Lachenal
8             UK, Nepal   Richard Grant, Chris Bonington, Ang Nyima Sherpa
9                 India          Mohan S. Kohli, Sonam Gyatso, Sonam Girmi

                   psmtnote
0                       NaN
1                       NaN
2  Possibly climbed earlier
3                       NaN
4                       NaN
5                       NaN
6                       NaN
7                       NaN
8                       NaN
9                       NaN

[10 rows x 23 columns]

In [10]:
df_refer = pd.read_csv('refer.csv', encoding='latin1')
df_refer.head()

,expid,refid,ryear,rtype,rjrnl,rauthor,rtitle,rpublisher,rpubdate,rlanguage,rcitation,ryak94
0,KANG84101,1,1984,Journal,American Alpine Journal,"Matsuzawa, Tetsuro",NaN,NaN,1985.0,NaN,59:247-249 (1985),NaN
1,KANG84102,1,1984,Journal,American Alpine Journal,"Ball, Gary",NaN,NaN,1985.0,NaN,59:249-250 (1985),NaN
2,KANG84301,1,1984,Journal,American Alpine Journal,"Marshall, Roger",NaN,NaN,1985.0,NaN,59:250 (1985),NaN
3,KANG84401,1,1984,Book,NaN,"Bremer-Kamp, Cherie",Living on the Edge,NaN,1987.0,NaN,NaN,B558
4,YALU84302,1,1984,Journal,American Alpine Journal,"Muller, Bernard",NaN,NaN,1985.0,NaN,59:251 (1985),NaN

Antes de hacer la limpieza de las columnas, voy a reemplazar los valores nulos por la media o el promedio en caso de que sea necesario. Las columnas con un % de nulos muy altos seran eliminadas

In [11]:
df_exped.info_modulo = info_modulo(df_exped)
df_exped.info_modulo.variables_null()

   Nombre Variable Cantidad de Nulos
0           route1               150
1           route2             11065
2           route3             11395
3           route4             11420
4          leaders                24
5          sponsor               816
6          ascent1              8647
7          ascent2             11324
8          ascent3             11414
9          ascent4             11421
10       countries              7312
11        approach              5989
12          bcdate              1630
13         smtdate               755
14         smttime              6443
15         smtdays              1754
16         totdays              3019
17        termdate              2975
18        termnote              6777
19       othersmts              9226
20       campsites               379
21       accidents              8424
22      achievment             10449
23          agency              1729
24          primid             10672

In [12]:
#DataFrame con los datos proporcionados
datos_nulos = [
    {"Nombre Variable": "route1", "Cantidad de Nulos": 150},
    {"Nombre Variable": "route2", "Cantidad de Nulos": 11065},
    {"Nombre Variable": "route3", "Cantidad de Nulos": 11395},
    {"Nombre Variable": "route4", "Cantidad de Nulos": 11420},
    {"Nombre Variable": "leaders", "Cantidad de Nulos": 24},
    {"Nombre Variable": "sponsor", "Cantidad de Nulos": 816},
    {"Nombre Variable": "ascent1", "Cantidad de Nulos": 8647},
    {"Nombre Variable": "ascent2", "Cantidad de Nulos": 11324},
    {"Nombre Variable": "ascent3", "Cantidad de Nulos": 11414},
    {"Nombre Variable": "ascent4", "Cantidad de Nulos": 11421},
    {"Nombre Variable": "countries", "Cantidad de Nulos": 7312},
    {"Nombre Variable": "approach", "Cantidad de Nulos": 5989},
    {"Nombre Variable": "bcdate", "Cantidad de Nulos": 1630},
    {"Nombre Variable": "smtdate", "Cantidad de Nulos": 755},
    {"Nombre Variable": "smttime", "Cantidad de Nulos": 6443},
    {"Nombre Variable": "smtdays", "Cantidad de Nulos": 1754},
    {"Nombre Variable": "totdays", "Cantidad de Nulos": 3019},
    {"Nombre Variable": "termdate", "Cantidad de Nulos": 2975},
    {"Nombre Variable": "termnote", "Cantidad de Nulos": 6777},
    {"Nombre Variable": "othersmts", "Cantidad de Nulos": 9226},
    {"Nombre Variable": "campsites", "Cantidad de Nulos": 379},
    {"Nombre Variable": "accidents", "Cantidad de Nulos": 8424},
    {"Nombre Variable": "achievment", "Cantidad de Nulos": 10449},
    {"Nombre Variable": "agency", "Cantidad de Nulos": 1729},
    {"Nombre Variable": "primid", "Cantidad de Nulos": 10672},
]

df_nulos = pd.DataFrame(datos_nulos)
df_nulos["% Nulos"] = (df_nulos["Cantidad de Nulos"] / len(df_exped)) * 100
df_nulos["% Nulos"] = df_nulos["% Nulos"].round(2)
df_nulos

   Nombre Variable  Cantidad de Nulos  % Nulos
0           route1                150     1.31
1           route2              11065    96.85
2           route3              11395    99.74
3           route4              11420    99.96
4          leaders                 24     0.21
5          sponsor                816     7.14
6          ascent1               8647    75.68
7          ascent2              11324    99.12
8          ascent3              11414    99.90
9          ascent4              11421    99.96
10       countries               7312    64.00
11        approach               5989    52.42
12          bcdate               1630    14.27
13         smtdate                755     6.61
14         smttime               6443    56.39
15         smtdays               1754    15.35
16         totdays               3019    26.42
17        termdate               2975    26.04
18        termnote               6777    59.32
19       othersmts               9226    80.75
20       campsites                379     3.32
21       accidents               8424    73.73
22      achievment              10449    91.46
23          agency               1729    15.13
24          primid              10672    93.41

In [13]:
df_exped.info_modulo = info_modulo(df_exped)
df_exped.info_modulo.variables_nan()

   Nombre Variable Cantidad de Nan o vacíos
0           route1                      150
1           route2                    11065
2           route3                    11395
3           route4                    11420
4          leaders                       24
5          sponsor                      816
6          ascent1                     8647
7          ascent2                    11324
8          ascent3                    11414
9          ascent4                    11421
10       countries                     7312
11        approach                     5989
12          bcdate                     1630
13         smtdate                      755
14        termdate                     2975
15        termnote                     6777
16       othersmts                     9226
17       campsites                      379
18       accidents                     8424
19      achievment                    10449
20          agency                     1729
21          primid                    10672

In [14]:
datos_nan = [
    {"Nombre Variable": "route1", "Cantidad de Nulos": 150},
    {"Nombre Variable": "route2", "Cantidad de Nulos": 11065},
    {"Nombre Variable": "route3", "Cantidad de Nulos": 11395},
    {"Nombre Variable": "route4", "Cantidad de Nulos": 11420},
    {"Nombre Variable": "leaders", "Cantidad de Nulos": 24},
    {"Nombre Variable": "sponsor", "Cantidad de Nulos": 816},
    {"Nombre Variable": "ascent1", "Cantidad de Nulos": 8647},
    {"Nombre Variable": "ascent2", "Cantidad de Nulos": 11324},
    {"Nombre Variable": "ascent3", "Cantidad de Nulos": 11414},
    {"Nombre Variable": "ascent4", "Cantidad de Nulos": 11421},
    {"Nombre Variable": "countries", "Cantidad de Nulos": 7312},
    {"Nombre Variable": "approach", "Cantidad de Nulos": 5989},
    {"Nombre Variable": "bcdate", "Cantidad de Nulos": 1630},
    {"Nombre Variable": "smtdate", "Cantidad de Nulos": 755},
    {"Nombre Variable": "smttime", "Cantidad de Nulos": 6443},
    {"Nombre Variable": "smtdays", "Cantidad de Nulos": 1754},
    {"Nombre Variable": "totdays", "Cantidad de Nulos": 3019},
    {"Nombre Variable": "termdate", "Cantidad de Nulos": 2975},
    {"Nombre Variable": "termnote", "Cantidad de Nulos": 6777},
    {"Nombre Variable": "othersmts", "Cantidad de Nulos": 9226},
    {"Nombre Variable": "campsites", "Cantidad de Nulos": 379},
    {"Nombre Variable": "accidents", "Cantidad de Nulos": 8424},
    {"Nombre Variable": "achievment", "Cantidad de Nulos": 10449},
    {"Nombre Variable": "agency", "Cantidad de Nulos": 1729},
    {"Nombre Variable": "primid", "Cantidad de Nulos": 10672},
]

df_nulos = pd.DataFrame(datos_nulos)
df_nulos["% Nulos"] = (df_nulos["Cantidad de Nulos"] / len(df_exped)) * 100
df_nulos["% Nulos"] = df_nulos["% Nulos"].round(2)
df_nulos

   Nombre Variable  Cantidad de Nulos  % Nulos
0           route1                150     1.31
1           route2              11065    96.85
2           route3              11395    99.74
3           route4              11420    99.96
4          leaders                 24     0.21
5          sponsor                816     7.14
6          ascent1               8647    75.68
7          ascent2              11324    99.12
8          ascent3              11414    99.90
9          ascent4              11421    99.96
10       countries               7312    64.00
11        approach               5989    52.42
12          bcdate               1630    14.27
13         smtdate                755     6.61
14         smttime               6443    56.39
15         smtdays               1754    15.35
16         totdays               3019    26.42
17        termdate               2975    26.04
18        termnote               6777    59.32
19       othersmts               9226    80.75
20       campsites                379     3.32
21       accidents               8424    73.73
22      achievment              10449    91.46
23          agency               1729    15.13
24          primid              10672    93.41

In [15]:

class modelo_ml():
    def __init__(self, x, y):
        # inicialización
        self.x = x
        self.y = y
    
    def escalar_data(self, x, funcion):
        scaler = funcion
        X_scaled = scaler.fit_transform(x)
        return X_scaled

    def division_datos(self, tamano, seed_number, estratifica='NO'):
        if (estratifica.upper() == 'NO'):
            X_train, X_test, y_train, y_test = train_test_split(self.x, self.y, test_size=tamano, random_state=seed_number)
        else:
            X_train, X_test, y_train, y_test = train_test_split(self.x, self.y, test_size=tamano, random_state=seed_number, stratify=self.y)
        return X_train, X_test, y_train, y_test

    def entrenar_modelo(self, modelo, seed_number, funcion_escalado, estimador='mean_squared_error', tamano=0.2, escalar='NO', tipo='REGRESION', estratifica='NO'):
        X_train, X_test, y_train, y_test = modelo_ml.division_datos(self, tamano, seed_number, estratifica)
        # Necesitamos escalar?
        if (escalar.upper() == 'SI'):
            X_train_escalada = modelo_ml.escalar_data(self, X_train, funcion_escalado)
            X_test_escalada = modelo_ml.escalar_data(self, X_test, funcion_escalado)
        else:
            X_train_escalada = X_train
            X_test_escalada = X_test

        model_train = modelo.fit(X_train_escalada, y_train)
        y_pred_train = model_train.predict(X_train_escalada)
        y_pred = model_train.predict(X_test_escalada)

        if (tipo.upper() == 'CLASIFICACION'):
            if estimador == 'accuracy':
                train_score = accuracy_score(y_train, y_pred_train)
                test_score = accuracy_score(y_test, y_pred)
            elif estimador == 'recall':
                train_score = recall_score(y_train, y_pred_train)
                test_score = recall_score(y_test, y_pred)
            elif estimador == 'f1_score':
                train_score = f1_score(y_train, y_pred_train)
                test_score = f1_score(y_test, y_pred)
            elif estimador == 'roc':
                train_score = roc_auc_score(y_train, model_train.predict_proba(X_train_escalada)[:, 1])
                test_score = roc_auc_score(y_test, model_train.predict_proba(X_test_escalada)[:, 1])
            modelo_ml.matriz_confusion(self, y_test, y_pred)
        else:
            if estimador == 'mean_squared_error':
                train_score = mean_squared_error(y_train, y_pred_train)
                test_score = mean_squared_error(y_test, y_pred)
            elif estimador == 'mean_absolute_error':
                train_score = mean_absolute_error(y_train, y_pred_train)
                test_score = mean_absolute_error(y_test, y_pred)
            elif estimador == 'r2_score':
                train_score = r2_score(y_train, y_pred_train)
                test_score = r2_score(y_test, y_pred)

        print("Entrenamiento estimación : " , train_score)
        print("Entrenamiento score R2 :", model_train.score(X_train_escalada, y_train))
        print("Prueba estimación : ", test_score)
        print("Prueba score R2 :", model_train.score(X_test_escalada, y_test))

        return X_train, X_train_escalada, y_train, X_test, X_test_escalada, y_test, y_pred, train_score, test_score

In [16]:
class limpiar_datos():
    def __init__(self, data):
        self.data = data
        self.categoricas_transformadas = []
        self.columnas_eliminadas = []
        self.columnas_imputadas = {}

    def transform_categoricas(self, categoricas_columnas):
        for c in categoricas_columnas:
            encoder = LabelEncoder()
            self.data[c] = encoder.fit_transform(self.data[c].astype(str))
            self.categoricas_transformadas.append(c)

    def eliminar_valores(self, porcnull_aceptable=35, indicacion='NO'):
        # Detección de columnas categóricas
        categorical_data_cols = [col for col in self.data.columns if self.data[col].dtype == 'O']
        if categorical_data_cols:
            self.transform_categoricas(categorical_data_cols)
            print(f"Columnas categóricas transformadas: {self.categoricas_transformadas}")
        else:
            print("El dataset no cuenta con columnas categóricas")

        # Detección de columnas con nulos
        x_columns = self.data.columns[self.data.isnull().any()]
        if not x_columns.empty:
            for col in x_columns:
                porc_null = (self.data[col].isnull().sum() * 100) / self.data.shape[0]
                if porc_null >= porcnull_aceptable:
                    self.data.drop(col, axis=1, inplace=True)
                    self.columnas_eliminadas.append(col)
                else:
                    if indicacion.upper() == 'BORRACOL':
                        self.data.drop(col, axis=1, inplace=True)
                        self.columnas_eliminadas.append(col)
                    elif indicacion.upper() == 'BORRAFILA':
                        self.data.dropna(subset=[col], inplace=True)
                        self.columnas_eliminadas.append(col)
                    elif indicacion.upper() == 'METKNN':
                        imputer = KNNImputer(n_neighbors=5, weights="uniform")
                        self.data[col] = imputer.fit_transform(self.data[[col]])
                        self.columnas_imputadas[col] = 'KNN'
                    elif indicacion.upper() == 'METMEDIA':
                        model = SimpleImputer(strategy='mean')
                        self.data[col] = model.fit_transform(self.data[[col]])
                        self.columnas_imputadas[col] = 'Media'
                    elif indicacion.upper() == 'METMODA':
                        model = SimpleImputer(strategy='most_frequent')
                        self.data[col] = model.fit_transform(self.data[[col]])
                        self.columnas_imputadas[col] = 'Moda'
                    else:
                        print(f"No se imputó la columna {col}")
        else:
            print("No existen datos nulos que imputar")

        # Resumen
        print(f"Columnas eliminadas: {self.columnas_eliminadas}")
        if self.columnas_imputadas:
            print("Columnas imputadas y método utilizado:")
            for col, metodo in self.columnas_imputadas.items():
                print(f"  {col}: {metodo}")
        return self.data

all_columns = list(df_exped.columns)
categoricas_columnas = [columns for columns in all_columns if df_exped[columns].dtype == 'object']
numericas_columnas = [columns for columns in all_columns if columns not in categoricas_columnas]
print(f'columnas continuas: {numericas_columnas}')
print(f'columnas categoricas: {categoricas_columnas}')

In [17]:
df_exped2 = df_exped.copy()
df_exped2.drop(columns=['route2', 'route3', 'route4', 'ascent1', 'ascent2', 'ascent3', 'ascent4','countries','approach', 'smttime','termnote','othersmts', 'accidents', 'achievment','primid','success2','success3','success4'], inplace=True)

In [18]:
df_exped2.limpiar_datos = limpiar_datos(df_exped2)
df_exped2.limpiar_datos.eliminar_valores(porcnull_aceptable=30, indicacion='METKNN')

Columnas categóricas transformadas: ['expid', 'peakid', 'season', 'host', 'route1', 'nation', 'leaders', 'sponsor', 'bcdate', 'smtdate', 'termdate', 'termreason', 'campsites', 'agency']
Columnas eliminadas: []
Columnas imputadas y método utilizado:
  smtdays: KNN
  totdays: KNN

,expid,peakid,year,season,host,route1,nation,leaders,sponsor,success1,...,o2taken,o2unkwn,campsites,agency,comrte,stdrte,primrte,primmem,primref,chksum
0,1864,8,1960,1,2,608,88,2220,9160,True,...,False,False,4894,978,False,False,False,False,False,2442047
1,1865,8,1969,0,2,608,99,125,6294,True,...,False,False,10216,978,False,False,False,False,False,2445501
2,1867,8,1973,1,2,1199,43,5997,7361,True,...,False,False,5299,978,False,False,False,False,False,2446797
3,1870,8,1978,0,2,351,88,4654,1936,False,...,False,False,2433,978,False,False,False,False,False,2448822
4,1871,8,1979,0,2,351,88,4265,9160,False,...,False,False,9424,978,False,False,False,False,False,2449204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11420,10365,299,2024,2,2,574,59,5707,6438,True,...,False,False,2691,978,False,False,False,False,False,2463218
11421,10567,325,2024,1,2,839,69,3289,478,False,...,False,False,10228,123,False,False,False,False,False,2789
11422,10814,328,2024,1,2,421,71,4986,7107,False,...,False,False,10537,471,False,False,False,False,False,2463320
11423,11256,393,2024,1,2,421,90,4230,5045,True,...,False,False,6982,977,False,False,False,False,False,2463393
11424,11420,415,2024,1,2,892,77,4362,9094,False,...,False,False,8269,171,False,False,False,False,False,2463459

In [19]:
df_exped2.info_modulo = info_modulo(df_exped2)
df_exped2.info_modulo.info_dataframe()

Tamaño: (11425, 47)


Variables nulos:
Empty DataFrame
Columns: [Nombre Variable, Cantidad de Nulos]
Index: []


Variables NAN:
Empty DataFrame
Columns: [Nombre Variable, Cantidad de Nan o vacíos]
Index: []


Informacion dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11425 entries, 0 to 11424
Data columns (total 47 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   expid       11425 non-null  int64
 1   peakid      11425 non-null  int64
 2   year        11425 non-null  int64
 3   season      11425 non-null  int64
 4   host        11425 non-null  int64
 5   route1      11425 non-null  int64
 6   nation      11425 non-null  int64
 7   leaders     11425 non-null  int64
 8   sponsor     11425 non-null  int64
 9   success1    11425 non-null  bool
 10  claimed     11425 non-null  bool
 11  disputed    11425 non-null  bool
 12  bcdate      11425 non-null  int64
 13  smtdate     11425 non-null  int64
 14  smtdays     11425 non-null  float64
 15  totdays     11425 non-null  float64
 16  termdate    11425 non-null  int64
 17  termreason  11425 non-null  int64
 18  highpoint   11425 non-null  int64
 19  traverse    11425 non-null  bool
 20  ski         11425 non-null  bool
 21  parapente   11425 non-null  bool
 22  camps       11425 non-null  int64
 23  rope        11425 non-null  int64
 24  totmembers  11425 non-null  int64
 25  smtmembers  11425 non-null  int64
 26  mdeaths     11425 non-null  int64
 27  tothired    11425 non-null  int64
 28  smthired    11425 non-null  int64
 29  hdeaths     11425 non-null  int64
 30  nohired     11425 non-null  bool
 31  o2used      11425 non-null  bool
 32  o2none      11425 non-null  bool
 33  o2climb     11425 non-null  bool
 34  o2descent   11425 non-null  bool
 35  o2sleep     11425 non-null  bool
 36  o2medical   11425 non-null  bool
 37  o2taken     11425 non-null  bool
 38  o2unkwn     11425 non-null  bool
 39  campsites   11425 non-null  int64
 40  agency      11425 non-null  int64
 41  comrte      11425 non-null  bool
 42  stdrte      11425 non-null  bool
 43  primrte     11425 non-null  bool
 44  primmem     11425 non-null  bool
 45  primref     11425 non-null  bool
 46  chksum      11425 non-null  int64
dtypes: bool(20), float64(2), int64(25)
memory usage: 2.6 MB
None


Datos:
   expid  peakid  year  season  host  route1  nation  leaders  sponsor  \
0   1864       8  1960       1     2     608      88     2220     9160
1   1865       8  1969       0     2     608      99      125     6294
2   1867       8  1973       1     2    1199      43     5997     7361
3   1870       8  1978       0     2     351      88     4654     1936
4   1871       8  1979       0     2     351      88     4265     9160
5   1872       8  1980       1     2     351      43     2152     5184
6   1873       8  1980       1     2     942      67     2451     5823
7   1875       8  1981       0     2     608      42      454     4961
8   1874       8  1981       0     2     810      43     4052     6686
9   1876       8  1982       0     2     670      43     2890     7743

   success1  ...  o2taken  o2unkwn  campsites  agency  comrte  stdrte  \
0      True  ...    False    False       4894     978   False   False
1      True  ...    False    False      10216     978   False   False
2      True  ...    False    False       5299     978   False   False
3     False  ...    False    False       2433     978   False   False
4     False  ...    False    False       9424     978   False   False
5     False  ...    False    False       7969     978   False   False
6     False  ...     True    False       2544     978   False   False
7     False  ...     True    False       1051     978   False   False
8     False  ...     True    False       1048     978   False   False
9     False  ...    False    False      10494     978   False   False

   primrte  primmem  primref   chksum
0    False    False    False  2442047
1    False    False    False  2445501
2    False    False    False  2446797
3    False    False    False  2448822
4    False    False    False  2449204
5    False    False    False  2449394
6    False    False    False  2449408
7    False    False    False  2449912
8    False    False    False  2449930
9    False    False    False  2450289

[10 rows x 47 columns]

In [20]:
df_exped2.corr().style.background_gradient(cmap ='coolwarm')

In [21]:
print(df_exped2['season'])

0        1
1        0
2        1
3        0
4        0
        ..
11420    2
11421    1
11422    1
11423    1
11424    1
Name: season, Length: 11425, dtype: int64